"""Configuration settings for the pharmacy sales analytics system."""

import os
from pathlib import Path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    # Get the directory where this config file is located
    BASE_DIR = Path(__file__).parent
    # Load .env file from the project root
    env_path = BASE_DIR / '.env'
    load_dotenv(dotenv_path=env_path)
except ImportError:
    # python-dotenv not installed, will use system environment variables
    BASE_DIR = Path(__file__).parent
    pass

# Project paths
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"
REPORTS_DIR = OUTPUT_DIR / "reports"
CHARTS_DIR = OUTPUT_DIR / "charts"

# Create directories if they don't exist
for directory in [DATA_DIR, OUTPUT_DIR, REPORTS_DIR, CHARTS_DIR]:
    directory.mkdir(exist_ok=True)

# Column names mapping
COLUMN_MAPPING = {
    'Item Code': 'item_code',
    'Item Name': 'item_name',
    'Units': 'units',
    'Pieces': 'pieces',
    'Quantity': 'quantity',
    'Selling Price': 'selling_price',
    'Total': 'total',
    'Sale Type': 'sale_type',
    'Customer Name': 'customer_name',
    'Date': 'date',
    'Time': 'time',
    'Category': 'category',
    'Receipt': 'receipt'
}

# Analysis parameters
RECENCY_WEIGHT = 1.0
FREQUENCY_WEIGHT = 1.0
MONETARY_WEIGHT = 1.0

# RFM scoring bins
RFM_BINS = 5

# Churn threshold (days)
CHURN_THRESHOLD_DAYS = 90

# Minimum support for association rules
# Note: These are starting thresholds. The system will automatically adjust lower if needed.
MIN_SUPPORT = 0.005  # 0.5% - More lenient than before (was 1%)
MIN_CONFIDENCE = 0.2  # 20% - Lowered for better recall (was 30%)
MIN_LIFT = 1.0  # Products appear together more than by chance

# Date format
DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

# Language settings
SUPPORTED_LANGUAGES = ['en', 'ar']
DEFAULT_LANGUAGE = 'en'

# Translations - Comprehensive dictionary for full localization
TRANSLATIONS = {
    'en': {
        # Main navigation
        'dashboard_title': 'Pharmacy Sales Analytics',
        'navigation': 'Navigation',
        'go_to': 'Go to',
        'data_info': 'Data Info',
        'upload_data': 'Upload Sales Data',
        'language': 'Language',
        
        # Menu items
        'sales_analysis': 'Sales Analysis',
        'customer_insights': 'Customer Insights',
        'product_performance': 'Product Performance',
        'rfm_segmentation': 'RFM Segmentation',
        'refill_prediction': 'Refill Prediction',
        'cross_sell_analysis': 'Cross-Sell Analysis',
        'ai_query': 'AI Query Assistant',
        'export_reports': 'Export & Reports',
        
        # Common metrics
        'total_revenue': 'Total Revenue',
        'total_orders': 'Total Orders',
        'avg_order_value': 'Avg Order Value',
        'unique_customers': 'Unique Customers',
        'records': 'Records',
        'date_range': 'Date Range',
        'customers': 'Customers',
        'products': 'Products',
        'orders': 'Orders',
        'to': 'to',
        
        # Sales Analysis
        'overall_performance': 'Overall Performance',
        'trends': 'Trends',
        'top_products': 'Top Products',
        'time_patterns': 'Time Patterns',
        'anomalies': 'Anomalies',
        'refunds': 'Refunds',
        'revenue_trends': 'Revenue Trends',
        
        # Refunds
        'refund_analysis': 'Refund Analysis',
        'no_refunds_found': 'No refunds found in the data.',
        'total_refunds': 'Total Refunds',
        'refund_transactions': 'Refund Transactions',
        'refund_rate': 'Refund Rate',
        'avg_refund_value': 'Avg Refund Value',
        'refunded_products': 'Refunded Products',
        'refund_customers': 'Refund Customers',
        'refund_trends': 'Refund Trends',
        'refund_details': 'Refund Details',
        'top_refunded_products': 'Top Refunded Products',
        'products_by_refund_amount': 'Products by Refund Amount',
        'customers_with_most_refunds': 'Customers with Most Refunds',
        'customers_by_refund_amount': 'Customers by Refund Amount',
        'refund_trends_over_time': 'Refund Trends Over Time',
        'monthly_refund_trend': 'Monthly Refund Trend',
        'monthly_refund_orders': 'Monthly Refund Orders',
        'refund_orders': 'Refund Orders',
        'refund_transaction_details': 'Refund Transaction Details',
        'filtered_refunds': 'Filtered Refunds',
        'filter_by_product': 'Filter by Product',
        'all_products': 'All Products',
        'no_refund_transactions': 'No refund transactions found.',
        'download_refund_data': 'Download Refund Data',
        'refund_amount': 'Refund Amount',
        'refund_quantity': 'Refund Quantity',
        'no_data_available': 'No data available',
        'select_period': 'Select Period',
        'daily': 'Daily',
        'weekly': 'Weekly',
        'monthly': 'Monthly',
        'daily_revenue_trend': 'Daily Revenue Trend',
        'weekly_revenue_trend': 'Weekly Revenue Trend',
        'monthly_revenue_trend': 'Monthly Revenue Trend',
        'date': 'Date',
        'revenue': 'Revenue',
        'daily_orders': 'Daily Orders',
        'weekly_orders': 'Weekly Orders',
        'monthly_orders': 'Monthly Orders',
        'daily_customers': 'Daily Unique Customers',
        'weekly_customers': 'Weekly Unique Customers',
        'monthly_customers': 'Monthly Unique Customers',
        'top_performing_products': 'Top Performing Products',
        'sort_by': 'Sort by',
        'quantity': 'Quantity',
        'number_of_products': 'Number of products',
        'top_categories': 'Top Categories',
        'revenue_by_category': 'Revenue by Category',
        'category': 'Category',
        'time_based_patterns': 'Time-based Patterns',
        'revenue_by_day_of_week': 'Revenue by Day of Week',
        'day': 'Day',
        'revenue_by_hour': 'Revenue by Hour of Day',
        'hour': 'Hour',
        'hour_of_day': 'Hour of Day',
        'anomaly_detection': 'Anomaly Detection',
        'anomaly_sensitivity': 'Anomaly sensitivity (% of data expected as anomalies)',
        'sales_anomaly_detection': 'Sales Anomaly Detection',
        'normal_days': 'Normal Days',
        'anomalous_days': 'Anomalies',
        'detected_anomalies': 'Detected Anomalies',
        'no_overdue_refills': 'No overdue refills!',
        
        # Customer Insights
        'customer_metrics': 'Customer Metrics',
        'total_customers': 'Total Customers',
        'repeat_customers': 'Repeat Customers',
        'repeat_rate': 'Repeat Rate',
        'avg_customer_ltv': 'Avg Customer LTV',
        'valuable_customers': 'Valuable Customers',
        'churn_risk': 'Churn Risk',
        'segments': 'Segments',
        'new_customers': 'New Customers',
        'high_value_customers': 'High-Value Customers (by Spend)',
        'frequent_buyers': 'Frequent Buyers',
        'churn_risk_analysis': 'Churn Risk Analysis',
        'inactivity_threshold': 'Inactivity threshold (days)',
        'found_customers_at_risk': 'Found {n} customers at risk of churning',
        'churn_risk_customers': 'Churn Risk Customers (Size = Order Count)',
        'days_since_last_purchase': 'Days Since Last Purchase',
        'total_spent': 'Total Spent',
        'no_customers_at_risk': 'No customers at risk of churning!',
        'customer_segmentation': 'Customer Segmentation by Value',
        'segment': 'Segment',
        'revenue_contribution': 'Revenue %',
        'avg_spend': 'Avg Spend',
        'customer_distribution': 'Customer Distribution by Segment',
        'revenue_contribution_by_segment': 'Revenue Contribution by Segment',
        'recent_period': 'Recent period (days)',
        'new_customers_in_period': '{n} new customers in the last {days} days',
        'no_new_customers': 'No new customers in the last {days} days',
        'daily_new_customer_acquisition': 'Daily New Customer Acquisition',
        
        # Product Performance
        'fast_slow_movers': 'Fast/Slow Movers',
        'abc_analysis': 'ABC Analysis',
        'lifecycle': 'Lifecycle',
        'inventory_signals': 'Inventory Signals',
        'fast_moving_products': 'Fast-Moving Products',
        'slow_moving_products': 'Slow-Moving Products',
        'abc_classification': 'ABC Classification',
        'abc_description': '**A-items:** Top 20% products generating 80% revenue\n**B-items:** Next 30% products generating 15% revenue\n**C-items:** Remaining 50% products generating 5% revenue',
        'revenue_by_abc_class': 'Revenue by ABC Class',
        'filter_by_class': 'Filter by class',
        'product_lifecycle_stages': 'Product Lifecycle Stages',
        'products_by_lifecycle': 'Products by Lifecycle Stage',
        'revenue_by_lifecycle': 'Revenue by Lifecycle Stage',
        'stage': 'Stage',
        'inventory_planning_signals': 'Inventory Planning Signals',
        'signal_summary': 'Signal Summary',
        'inventory_signals_distribution': 'Inventory Signals Distribution',
        'filter_by_signal': 'Filter by signal',
        'all': 'All',
        
        # RFM Segmentation
        'rfm_title': 'RFM Customer Segmentation',
        'rfm_description': '**Simple Customer Segmentation Based on Purchase Behavior:**',
        'rfm_new': '🆕 **New Customers**: Purchased only once',
        'rfm_potential': '🌱 **Potential Customers**: 2-5 purchases',
        'rfm_champions': '🏆 **Champions**: 6+ purchases, active recently',
        'rfm_loyal': '💎 **Loyal Customers**: 6+ purchases, still engaged',
        'rfm_at_risk': '⚠️ **At Risk**: Good customers becoming inactive',
        'rfm_lost': '😴 **Lost Customers**: Haven\'t purchased in 90+ days',
        'segment_overview': 'Segment Overview',
        'customer_distribution_by_segment': 'Customer Distribution by Segment',
        'revenue_by_segment': 'Revenue by Segment',
        'segment_details': 'Segment Details',
        'select_segment': 'Select segment to explore',
        'customers_count': '{n} customers',
        'recommended_actions': 'Recommended Actions',
        'priority': 'Priority',
        'goal': 'Goal',
        'actions': 'Actions',
        'rfm_distribution': 'RFM Distribution',
        'rfm_3d_scatter': '3D RFM Scatter Plot',
        'recency': 'Recency (days)',
        'frequency': 'Frequency (orders)',
        'monetary': 'Monetary',
        'understanding_metrics': '📖 Understanding the Metrics',
        'rfm_columns_explained': '**RFM Columns Explained:**',
        'segment_definitions': '**Segment Definitions:**',
        'tip_rfm': '💡 **Tip**: Focus on \'At Risk\' customers with win-back campaigns before they become \'Lost\'. Nurture \'Potential\' customers to become \'Champions\'!',
        
        # Refill Prediction
        'refill_title': 'Refill Prediction & Price Forecasting',
        'refill_description': '',
        'refill_dashboard': 'Refill Intelligence Dashboard',
        'tracked_pairs': 'Tracked Pairs',
        'avg_interval': 'Avg Interval',
        'overdue': 'Overdue',
        'upcoming_30d': 'Upcoming (30d)',
        'high_confidence': 'High Confidence',
        'overdue_refills': 'Overdue Refills',
        'upcoming_refills': 'Upcoming Refills',
        'customer_schedule': 'Customer Schedule',
        'price_predictions': 'Price Predictions',
        'grace_period': 'Grace period (days)',
        'overdue_detected': '{n} overdue refills detected!',
        'top_overdue': 'Top 20 Overdue Refills',
        'look_ahead': 'Look ahead (days)',
        'refills_expected': '{n} refills expected in the next {days} days',
        'refill_timeline': 'Refill Timeline (Next {days} Days)',
        'no_refills_expected': 'No refills expected in the next {days} days',
        'customer_refill_schedule': 'Customer Refill Schedule',
        'select_customer': 'Select customer',
        'no_refill_history': 'No refill history for this customer',
        'order_value_predictions': '💰 Order Value & Price Predictions',
        'advanced_metrics': '**Advanced Metrics:**',
        'top_predicted_values': '**Top 20 Predicted Order Values**',
        'price_trend_distribution': '**📈 Price Trend Distribution**',
        'price_trends_across': 'Price Trends Across Products',
        'increasing': 'Increasing',
        'stable': 'Stable',
        'decreasing': 'Decreasing',
        'regularity_distribution': '**🎯 Regularity Score Distribution**',
        'purchase_regularity': 'Purchase Regularity Distribution',
        'high_regularity': 'High (70+)',
        'medium_regularity': 'Medium (40-70)',
        'low_regularity': 'Low (<40)',
        'key_insights': '💡 Key Insights',
        'total_predicted_revenue': 'Total Predicted Revenue',
        'avg_confidence': 'Avg Confidence',
        'avg_regularity': 'Avg Regularity',
        'tip_refill': '💡 **Tip**: Focus on high regularity score customers for targeted refill reminders - they\'re more predictable!',
        'not_enough_data': 'Not enough data for price predictions',
        'first_order_date': 'First Order Date',
        'customer_relationship_age': 'Customer Relationship Age',
        'days_since_first_order': 'Days Since First Order',
        'confidence_breakdown': 'Confidence Score Breakdown',
        'customer_status': 'Customer Status',
        'likely_lost': 'Likely Lost',
        'at_high_risk': 'At High Risk',
        'at_risk': 'At Risk',
        'action_needed': 'Action Needed',
        'adjusted_confidence': 'Adjusted Confidence',
        'churn_probability': 'Churn Probability',
        'lost_customer_insight': 'Customers overdue by 6+ months are unlikely to return without intervention',
        'predicted_order_value': 'Predicted Order Value',
        'predicted_unit_price': 'Predicted Unit Price',
        'predicted_quantity': 'Predicted Quantity',
        'avg_price_per_unit': 'Avg Price Per Unit',
        'total_predicted_revenue': 'Total Predicted Revenue',
        'avg_order_value': 'Avg Order Value',
        'high_confidence_revenue': 'High Confidence Revenue',
        'expected_refills': 'Expected Refills',
        'revenue_forecast': 'Revenue Forecast',
        
        # Cross-Sell Analysis
        'cross_sell_title': 'Cross-Sell & Bundle Analysis',
        'market_basket_description': '**Market Basket Analysis** identifies products frequently purchased together.',
        'market_basket_helps': 'This helps with:\n- 🎁 Creating product bundles\n- 🔄 Cross-sell recommendations\n- 📊 Store layout optimization\n- 💡 Targeted promotions',
        'analysis_diagnostics': '📊 Analysis Diagnostics & Data Quality',
        'total_orders_diag': 'Total Orders',
        'unique_products_diag': 'Unique Products',
        'multi_item_orders': 'Multi-Item Orders',
        'multi_item_pct': 'Multi-Item %',
        'avg_basket_size': 'Avg Basket Size',
        'products_in_10plus': 'Products in 10+ Orders',
        'data_quality_notes': '**⚠️ Data Quality Notes:**',
        'product_bundles': 'Product Bundles',
        'product_associations': 'Product Associations',
        'market_basket': 'Market Basket',
        'recommendations': 'Recommendations',
        'suggested_bundles': 'Suggested Product Bundles',
        'bundles_description': 'Bundles are groups of products frequently purchased together in the same transaction.',
        'min_items_bundle': 'Min items in bundle',
        'max_items_bundle': 'Max items in bundle',
        'number_of_bundles': 'Number of bundles',
        'analyzing_bundles': 'Analyzing product bundles...',
        'found_bundles': '✓ Found {n} product bundles!',
        'bundle_details': '### Bundle Details',
        'bundle_items': '**Bundle Items:**',
        'bundle_metrics': '**Bundle Metrics:**',
        'no_bundles_found': '⚠️ No product bundles found with current settings.',
        'tips_improve': '**Tips to improve results:**',
        'product_affinity': 'Product Affinity Analysis',
        'affinity_description': '**Product affinity** shows which products are frequently purchased together.',
        'lift_description': '- **Lift > 1**: Products bought together more than expected by chance\n- **Confidence**: Probability of buying product B when product A is purchased',
        'calculating_associations': 'Calculating product associations...',
        'found_associations': '✓ Found {n} product associations!',
        'minimum_lift': 'Minimum Lift',
        'num_associations': 'Number of associations to show',
        'top_product_pairs': '**Top {n} Product Pairs (by Lift)**',
        'product_affinity_heatmap': '**Product Affinity Heatmap**',
        'no_associations': '⚠️ No product associations found.',
        'market_basket_insights': 'Market Basket Insights',
        'avg_items_per_basket': 'Avg Items per Basket',
        'avg_basket_value': 'Avg Basket Value',
        'max_items_basket': 'Max Items in Basket',
        'single_item_baskets': 'Single-Item Baskets',
        'multi_item_baskets': 'Multi-Item Baskets',
        'basket_size_distribution': 'Basket Size Distribution',
        'number_of_items': 'Number of Items',
        'number_of_orders': 'Number of Orders',
        'product_recommendations': 'Product Recommendations',
        'recommendations_description': 'Get personalized product recommendations based on purchase patterns.',
        'select_product': 'Select a product',
        'number_recommendations': 'Number of recommendations',
        'get_recommendations': 'Get Recommendations',
        'finding_complementary': 'Finding complementary products for \'{product}\'...',
        'found_complementary': '✓ Found {n} complementary products for \'{product}\'',
        'complementary_products_for': 'Complementary Products for {product}',
        'product': 'Product',
        'lift_score': 'Lift Score',
        'support': 'Support',
        'confidence': 'Confidence',
        'detailed_recommendations': '### Detailed Recommendations',
        'how_to_use': '### 💡 How to Use These Recommendations',
        'for_sales': '**For Sales:**',
        'for_merchandising': '**For Merchandising:**',
        'no_strong_associations': '⚠️ No strong associations found for \'{product}\'',
        
        # AI Query Assistant
        'ai_query_title': 'AI Query Assistant',
        'ai_query_description': 'Ask questions about your sales data in plain English. The AI will analyze your data and provide insights.',
        'gpt_enhanced': '✨ GPT Enhanced',
        'pattern_matching': '🔧 Pattern Matching',
        'gpt_caption': 'Using OpenAI for intelligent query interpretation and insights generation',
        'set_api_key': 'Set OPENAI_API_KEY for enhanced AI features',
        'example_questions': '📝 Example Questions You Can Ask',
        'ask_your_question': 'Ask Your Question',
        'choose_example': 'Choose an example or write your own:',
        'custom_question': 'Custom question...',
        'your_question': 'Your question:',
        'ask': '🔍 Ask',
        'analyzing': 'Analyzing...',
        'gpt_analysis_complete': '✨ GPT-Powered Analysis Complete',
        'analysis_complete': '✓ Analysis Complete',
        'answer': '**Answer:**',
        'ai_insights': '### 🧠 AI Insights',
        'detailed_data': 'Detailed Data',
        'download_results': 'Download Results as CSV',
        'suggested_followup': '### 💭 Suggested Follow-up Questions',
        'please_enter_question': 'Please enter a question',
        'ai_chat': '💬 AI Chat',
        'ai_chat_description': 'Have a conversation with the AI about your sales data',
        'chat_input_placeholder': 'Ask follow-up questions or have a conversation...',
        'thinking': 'Thinking...',
        'clear_chat': '🗑️ Clear Chat History',
        'automatic_insights': '🎯 Automatic Insights',
        'generating_insights': 'Generating insights...',
        'no_insights': 'No significant insights detected',
        
        # Export & Reports
        'export_title': 'Export & Reports',
        'generate_reports': 'Generate Reports',
        'select_report_type': 'Select Report Type',
        'sales_summary': 'Sales Summary',
        'customer_analysis': 'Customer Analysis',
        'product_performance_report': 'Product Performance',
        'rfm_segmentation_report': 'RFM Segmentation',
        'refill_predictions_report': 'Refill Predictions',
        'cross_sell_opportunities': 'Cross-Sell Opportunities',
        'generate_report': 'Generate Report',
        'generating_report': 'Generating report...',
        'download_csv': 'Download CSV',
        'report_generated': 'Report generated successfully!',
        
        # Common buttons and actions
        'loading': 'Loading sample data for demonstration...',
        'error_loading': 'Error loading data: {error}',
        'failed_to_load': 'Failed to load data. Please check your file.',
        'help_total_revenue': 'Total revenue from all sales',
        'help_unique_orders': 'Number of unique orders',
        'help_unique_customers': 'Number of unique customers',
        'help_avg_order': 'Average value per order',
        'days': 'days',
        'items': 'items',
        'times': 'times',
        'bundle': 'Bundle',
        'trend': 'Trend',
        'count': 'Count',
        'class': 'Class',
        'regularity': 'Regularity',
    },
    'ar': {
        # Main navigation
        'dashboard_title': 'تحليلات مبيعات الصيدلية',
        'navigation': 'التنقل',
        'go_to': 'اذهب إلى',
        'data_info': 'معلومات البيانات',
        'upload_data': 'رفع بيانات المبيعات',
        'language': 'اللغة',
        
        # Menu items
        'sales_analysis': 'تحليل المبيعات',
        'customer_insights': 'رؤى العملاء',
        'product_performance': 'أداء المنتجات',
        'rfm_segmentation': 'تصنيف العملاء',
        'refill_prediction': 'توقع إعادة الشراء',
        'cross_sell_analysis': 'البيع المتقاطع',
        'ai_query': 'مساعد الذكاء الاصطناعي',
        'export_reports': 'التقارير والتصدير',
        
        # Common metrics
        'total_revenue': 'إجمالي الإيرادات',
        'total_orders': 'إجمالي الطلبات',
        'avg_order_value': 'متوسط قيمة الطلب',
        'unique_customers': 'عدد العملاء',
        'records': 'السجلات',
        'date_range': 'نطاق التاريخ',
        'customers': 'العملاء',
        'products': 'المنتجات',
        'orders': 'الطلبات',
        'to': 'إلى',
        
        # Sales Analysis
        'overall_performance': 'الأداء العام',
        'trends': 'الاتجاهات',
        'top_products': 'المنتجات الأفضل',
        'time_patterns': 'الأنماط الزمنية',
        'anomalies': 'الحالات الشاذة',
        'refunds': 'المرتجعات',
        'revenue_trends': 'اتجاهات الإيرادات',
        
        # Refunds
        'refund_analysis': 'تحليل المرتجعات',
        'no_refunds_found': 'لم يتم العثور على مرتجعات في البيانات.',
        'total_refunds': 'إجمالي المرتجعات',
        'refund_transactions': 'معاملات المرتجعات',
        'refund_rate': 'نسبة المرتجعات',
        'avg_refund_value': 'متوسط قيمة المرتجع',
        'refunded_products': 'المنتجات المرتجعة',
        'refund_customers': 'عملاء المرتجعات',
        'refund_trends': 'اتجاهات المرتجعات',
        'refund_details': 'تفاصيل المرتجعات',
        'top_refunded_products': 'المنتجات الأكثر إرجاعاً',
        'products_by_refund_amount': 'المنتجات حسب قيمة المرتجعات',
        'customers_with_most_refunds': 'العملاء الأكثر إرجاعاً',
        'customers_by_refund_amount': 'العملاء حسب قيمة المرتجعات',
        'refund_trends_over_time': 'اتجاهات المرتجعات عبر الوقت',
        'monthly_refund_trend': 'اتجاه المرتجعات الشهري',
        'monthly_refund_orders': 'طلبات المرتجعات الشهرية',
        'refund_orders': 'طلبات المرتجعات',
        'refund_transaction_details': 'تفاصيل معاملات المرتجعات',
        'filtered_refunds': 'المرتجعات المصفاة',
        'filter_by_product': 'تصفية حسب المنتج',
        'all_products': 'كل المنتجات',
        'no_refund_transactions': 'لم يتم العثور على معاملات مرتجعات.',
        'download_refund_data': 'تحميل بيانات المرتجعات',
        'refund_amount': 'قيمة المرتجع',
        'refund_quantity': 'كمية المرتجعات',
        'no_data_available': 'لا توجد بيانات متاحة',
        'select_period': 'اختر الفترة',
        'daily': 'يومي',
        'weekly': 'أسبوعي',
        'monthly': 'شهري',
        'daily_revenue_trend': 'اتجاه الإيرادات اليومي',
        'weekly_revenue_trend': 'اتجاه الإيرادات الأسبوعي',
        'monthly_revenue_trend': 'اتجاه الإيرادات الشهري',
        'date': 'التاريخ',
        'revenue': 'الإيرادات',
        'daily_orders': 'الطلبات اليومية',
        'weekly_orders': 'الطلبات الأسبوعية',
        'monthly_orders': 'الطلبات الشهرية',
        'daily_customers': 'العملاء اليوميون',
        'weekly_customers': 'العملاء الأسبوعيون',
        'monthly_customers': 'العملاء الشهريون',
        'top_performing_products': 'المنتجات الأفضل أداءً',
        'sort_by': 'ترتيب حسب',
        'quantity': 'الكمية',
        'number_of_products': 'عدد المنتجات',
        'top_categories': 'الفئات الأفضل',
        'revenue_by_category': 'الإيرادات حسب الفئة',
        'category': 'الفئة',
        'time_based_patterns': 'الأنماط الزمنية',
        'revenue_by_day_of_week': 'الإيرادات حسب يوم الأسبوع',
        'day': 'اليوم',
        'revenue_by_hour': 'الإيرادات حسب ساعة اليوم',
        'hour': 'الساعة',
        'hour_of_day': 'ساعة اليوم',
        'anomaly_detection': 'كشف الحالات الشاذة',
        'anomaly_sensitivity': 'حساسية الحالات الشاذة (٪ من البيانات المتوقعة كحالات شاذة)',
        'sales_anomaly_detection': 'كشف الحالات الشاذة في المبيعات',
        'normal_days': 'أيام عادية',
        'anomalous_days': 'حالات شاذة',
        'detected_anomalies': 'الحالات الشاذة المكتشفة',
        'no_overdue_refills': 'لا توجد إعادة شراء متأخرة!',
        
        # Customer Insights
        'customer_metrics': 'مقاييس العملاء',
        'total_customers': 'إجمالي العملاء',
        'repeat_customers': 'العملاء المتكررون',
        'repeat_rate': 'معدل التكرار',
        'avg_customer_ltv': 'متوسط القيمة الدائمة للعميل',
        'valuable_customers': 'العملاء القيمون',
        'churn_risk': 'خطر فقدان العملاء',
        'segments': 'الشرائح',
        'new_customers': 'عملاء جدد',
        'high_value_customers': 'العملاء ذوو القيمة العالية (حسب الإنفاق)',
        'frequent_buyers': 'المشترون المتكررون',
        'churn_risk_analysis': 'تحليل خطر فقدان العملاء',
        'inactivity_threshold': 'عتبة عدم النشاط (أيام)',
        'found_customers_at_risk': 'تم العثور على {n} عميل معرض لخطر الفقدان',
        'churn_risk_customers': 'عملاء معرضون لخطر الفقدان (الحجم = عدد الطلبات)',
        'days_since_last_purchase': 'أيام منذ آخر شراء',
        'total_spent': 'إجمالي الإنفاق',
        'no_customers_at_risk': 'لا يوجد عملاء معرضون لخطر الفقدان!',
        'customer_segmentation': 'تصنيف العملاء حسب القيمة',
        'segment': 'الشريحة',
        'revenue_contribution': '٪ الإيرادات',
        'avg_spend': 'متوسط الإنفاق',
        'customer_distribution': 'توزيع العملاء حسب الشريحة',
        'revenue_contribution_by_segment': 'مساهمة الإيرادات حسب الشريحة',
        'recent_period': 'الفترة الأخيرة (أيام)',
        'new_customers_in_period': '{n} عميل جديد في آخر {days} يوم',
        'no_new_customers': 'لا يوجد عملاء جدد في آخر {days} يوم',
        'daily_new_customer_acquisition': 'اكتساب العملاء الجدد يومياً',
        
        # Product Performance
        'fast_slow_movers': 'المنتجات السريعة/البطيئة',
        'abc_analysis': 'تحليل ABC',
        'lifecycle': 'دورة الحياة',
        'inventory_signals': 'إشارات المخزون',
        'fast_moving_products': 'منتجات سريعة الحركة',
        'slow_moving_products': 'منتجات بطيئة الحركة',
        'abc_classification': 'تصنيف ABC',
        'abc_description': '**منتجات A:** أفضل 20٪ من المنتجات تحقق 80٪ من الإيرادات\n**منتجات B:** التالي 30٪ من المنتجات تحقق 15٪ من الإيرادات\n**منتجات C:** الباقي 50٪ من المنتجات تحقق 5٪ من الإيرادات',
        'revenue_by_abc_class': 'الإيرادات حسب فئة ABC',
        'filter_by_class': 'تصفية حسب الفئة',
        'product_lifecycle_stages': 'مراحل دورة حياة المنتج',
        'products_by_lifecycle': 'المنتجات حسب مرحلة دورة الحياة',
        'revenue_by_lifecycle': 'الإيرادات حسب مرحلة دورة الحياة',
        'stage': 'المرحلة',
        'inventory_planning_signals': 'إشارات تخطيط المخزون',
        'signal_summary': 'ملخص الإشارات',
        'inventory_signals_distribution': 'توزيع إشارات المخزون',
        'filter_by_signal': 'تصفية حسب الإشارة',
        'all': 'الكل',
        
        # RFM Segmentation
        'rfm_title': 'تصنيف العملاء RFM',
        'rfm_description': '**تصنيف بسيط للعملاء بناءً على سلوك الشراء:**',
        'rfm_new': '🆕 **عملاء جدد**: اشتروا مرة واحدة فقط',
        'rfm_potential': '🌱 **عملاء محتملون**: 2-5 مشتريات',
        'rfm_champions': '🏆 **أبطال**: 6+ مشتريات، نشطون مؤخراً',
        'rfm_loyal': '💎 **عملاء مخلصون**: 6+ مشتريات، ما زالوا متفاعلين',
        'rfm_at_risk': '⚠️ **معرضون للخطر**: عملاء جيدون يصبحون غير نشطين',
        'rfm_lost': '😴 **عملاء مفقودون**: لم يشتروا منذ 90+ يوم',
        'segment_overview': 'نظرة عامة على الشرائح',
        'customer_distribution_by_segment': 'توزيع العملاء حسب الشريحة',
        'revenue_by_segment': 'الإيرادات حسب الشريحة',
        'segment_details': 'تفاصيل الشريحة',
        'select_segment': 'اختر شريحة للاستكشاف',
        'customers_count': '{n} عميل',
        'recommended_actions': 'الإجراءات الموصى بها',
        'priority': 'الأولوية',
        'goal': 'الهدف',
        'actions': 'الإجراءات',
        'rfm_distribution': 'توزيع RFM',
        'rfm_3d_scatter': 'رسم بياني ثلاثي الأبعاد RFM',
        'recency': 'الحداثة (أيام)',
        'frequency': 'التكرار (طلبات)',
        'monetary': 'القيمة المالية',
        'understanding_metrics': '📖 فهم المقاييس',
        'rfm_columns_explained': '**شرح أعمدة RFM:**',
        'segment_definitions': '**تعريفات الشرائح:**',
        'tip_rfm': '💡 **نصيحة**: ركز على العملاء "المعرضين للخطر" بحملات الاسترجاع قبل أن يصبحوا "مفقودين". اهتم بالعملاء "المحتملين" ليصبحوا "أبطال"!',
        
        # Refill Prediction
        'refill_title': 'التنبؤ المتقدم بإعادة الشراء وتوقع الأسعار',
        'refill_description': '',
        'refill_dashboard': 'لوحة معلومات إعادة الشراء',
        'tracked_pairs': 'أزواج متتبعة',
        'avg_interval': 'متوسط الفترة',
        'overdue': 'متأخر',
        'upcoming_30d': 'قادم (30 يوم)',
        'high_confidence': 'ثقة عالية',
        'overdue_refills': 'إعادة شراء متأخرة',
        'upcoming_refills': 'إعادة شراء قادمة',
        'customer_schedule': 'جدول العميل',
        'price_predictions': 'توقعات الأسعار',
        'grace_period': 'فترة السماح (أيام)',
        'overdue_detected': 'تم اكتشاف {n} إعادة شراء متأخرة!',
        'top_overdue': 'أفضل 20 إعادة شراء متأخرة',
        'look_ahead': 'النظر للأمام (أيام)',
        'refills_expected': '{n} إعادة شراء متوقعة في الـ {days} يوم القادمة',
        'refill_timeline': 'جدول إعادة الشراء (الـ {days} يوم القادمة)',
        'no_refills_expected': 'لا توجد إعادة شراء متوقعة في الـ {days} يوم القادمة',
        'customer_refill_schedule': 'جدول إعادة شراء العميل',
        'select_customer': 'اختر عميل',
        'no_refill_history': 'لا يوجد سجل إعادة شراء لهذا العميل',
        'order_value_predictions': '💰 توقعات قيمة الطلب والأسعار',
        'advanced_metrics': '**مقاييس متقدمة:**',
        'top_predicted_values': '**أعلى 20 قيمة طلب متوقعة**',
        'price_trend_distribution': '**📈 توزيع اتجاه الأسعار**',
        'price_trends_across': 'اتجاهات الأسعار عبر المنتجات',
        'increasing': 'متزايد',
        'stable': 'مستقر',
        'decreasing': 'متناقص',
        'regularity_distribution': '**🎯 توزيع نقاط الانتظام**',
        'purchase_regularity': 'توزيع انتظام الشراء',
        'high_regularity': 'عالي (70+)',
        'medium_regularity': 'متوسط (40-70)',
        'low_regularity': 'منخفض (<40)',
        'key_insights': '💡 رؤى رئيسية',
        'total_predicted_revenue': 'إجمالي الإيرادات المتوقعة',
        'avg_confidence': 'متوسط الثقة',
        'avg_regularity': 'متوسط الانتظام',
        'tip_refill': '💡 **نصيحة**: ركز على العملاء ذوي نقاط الانتظام العالية للتذكيرات المستهدفة - إنهم أكثر قابلية للتنبؤ!',
        'not_enough_data': 'لا توجد بيانات كافية لتوقعات الأسعار',
        'first_order_date': 'تاريخ الطلب الأول',
        'customer_relationship_age': 'عمر علاقة العميل',
        'days_since_first_order': 'أيام منذ الطلب الأول',
        'confidence_breakdown': 'تفصيل درجة الثقة',
        'customer_status': 'حالة العميل',
        'likely_lost': 'من المحتمل فقدانه',
        'at_high_risk': 'معرض لخطر كبير',
        'at_risk': 'معرض للخطر',
        'action_needed': 'يحتاج إلى إجراء',
        'adjusted_confidence': 'الثقة المعدلة',
        'churn_probability': 'احتمالية الفقدان',
        'lost_customer_insight': 'العملاء المتأخرون لأكثر من 6 أشهر من غير المحتمل أن يعودوا بدون تدخل',
        'predicted_order_value': 'قيمة الطلب المتوقعة',
        'predicted_unit_price': 'سعر الوحدة المتوقع',
        'predicted_quantity': 'الكمية المتوقعة',
        'avg_price_per_unit': 'متوسط سعر الوحدة',
        'total_predicted_revenue': 'إجمالي الإيرادات المتوقعة',
        'avg_order_value': 'متوسط قيمة الطلب',
        'high_confidence_revenue': 'إيرادات عالية الثقة',
        'expected_refills': 'إعادة الشراء المتوقعة',
        'revenue_forecast': 'توقع الإيرادات',
        
        # Cross-Sell Analysis
        'cross_sell_title': 'تحليل البيع المتقاطع والحزم',
        'market_basket_description': '**تحليل سلة السوق** يحدد المنتجات التي يتم شراؤها معاً بشكل متكرر.',
        'market_basket_helps': 'هذا يساعد في:\n- 🎁 إنشاء حزم المنتجات\n- 🔄 توصيات البيع المتقاطع\n- 📊 تحسين تخطيط المتجر\n- 💡 العروض الترويجية المستهدفة',
        'analysis_diagnostics': '📊 تشخيصات التحليل وجودة البيانات',
        'total_orders_diag': 'إجمالي الطلبات',
        'unique_products_diag': 'منتجات فريدة',
        'multi_item_orders': 'طلبات متعددة المنتجات',
        'multi_item_pct': '٪ متعدد المنتجات',
        'avg_basket_size': 'متوسط حجم السلة',
        'products_in_10plus': 'منتجات في 10+ طلبات',
        'data_quality_notes': '**⚠️ ملاحظات جودة البيانات:**',
        'product_bundles': 'حزم المنتجات',
        'product_associations': 'ارتباطات المنتجات',
        'market_basket': 'سلة السوق',
        'recommendations': 'التوصيات',
        'suggested_bundles': 'حزم المنتجات المقترحة',
        'bundles_description': 'الحزم هي مجموعات من المنتجات التي يتم شراؤها معاً بشكل متكرر في نفس المعاملة.',
        'min_items_bundle': 'الحد الأدنى من المنتجات في الحزمة',
        'max_items_bundle': 'الحد الأقصى من المنتجات في الحزمة',
        'number_of_bundles': 'عدد الحزم',
        'analyzing_bundles': 'تحليل حزم المنتجات...',
        'found_bundles': '✓ تم العثور على {n} حزمة منتجات!',
        'bundle_details': '### تفاصيل الحزمة',
        'bundle_items': '**منتجات الحزمة:**',
        'bundle_metrics': '**مقاييس الحزمة:**',
        'no_bundles_found': '⚠️ لم يتم العثور على حزم منتجات بالإعدادات الحالية.',
        'tips_improve': '**نصائح لتحسين النتائج:**',
        'product_affinity': 'تحليل التقارب بين المنتجات',
        'affinity_description': '**تقارب المنتجات** يُظهر المنتجات التي يتم شراؤها معاً بشكل متكرر.',
        'lift_description': '- **Lift > 1**: المنتجات تُشترى معاً أكثر من المتوقع بالصدفة\n- **Confidence**: احتمالية شراء المنتج B عند شراء المنتج A',
        'calculating_associations': 'حساب ارتباطات المنتجات...',
        'found_associations': '✓ تم العثور على {n} ارتباط منتج!',
        'minimum_lift': 'الحد الأدنى للرفع',
        'num_associations': 'عدد الارتباطات المراد عرضها',
        'top_product_pairs': '**أفضل {n} أزواج منتجات (حسب الرفع)**',
        'product_affinity_heatmap': '**خريطة حرارية لتقارب المنتجات**',
        'no_associations': '⚠️ لم يتم العثور على ارتباطات منتجات.',
        'market_basket_insights': 'رؤى سلة السوق',
        'avg_items_per_basket': 'متوسط المنتجات لكل سلة',
        'avg_basket_value': 'متوسط قيمة السلة',
        'max_items_basket': 'الحد الأقصى من المنتجات في السلة',
        'single_item_baskets': 'سلال أحادية المنتج',
        'multi_item_baskets': 'سلال متعددة المنتجات',
        'basket_size_distribution': 'توزيع حجم السلة',
        'number_of_items': 'عدد المنتجات',
        'number_of_orders': 'عدد الطلبات',
        'product_recommendations': 'توصيات المنتجات',
        'recommendations_description': 'احصل على توصيات منتجات مخصصة بناءً على أنماط الشراء.',
        'select_product': 'اختر منتج',
        'number_recommendations': 'عدد التوصيات',
        'get_recommendations': 'احصل على التوصيات',
        'finding_complementary': 'البحث عن منتجات تكميلية لـ \'{product}\'...',
        'found_complementary': '✓ تم العثور على {n} منتج تكميلي لـ \'{product}\'',
        'complementary_products_for': 'منتجات تكميلية لـ {product}',
        'product': 'المنتج',
        'lift_score': 'نقاط الرفع',
        'support': 'الدعم',
        'confidence': 'الثقة',
        'detailed_recommendations': '### التوصيات التفصيلية',
        'how_to_use': '### 💡 كيفية استخدام هذه التوصيات',
        'for_sales': '**للمبيعات:**',
        'for_merchandising': '**للتسويق:**',
        'no_strong_associations': '⚠️ لم يتم العثور على ارتباطات قوية لـ \'{product}\'',
        
        # AI Query Assistant
        'ai_query_title': 'مساعد الاستعلام بالذكاء الاصطناعي',
        'ai_query_description': 'اطرح أسئلة حول بيانات مبيعاتك بالعربية البسيطة. سيقوم الذكاء الاصطناعي بتحليل بياناتك وتوفير الرؤى.',
        'gpt_enhanced': '✨ محسّن بـ GPT',
        'pattern_matching': '🔧 مطابقة الأنماط',
        'gpt_caption': 'استخدام OpenAI لتفسير الاستعلام الذكي وتوليد الرؤى',
        'set_api_key': 'قم بتعيين OPENAI_API_KEY للحصول على ميزات الذكاء الاصطناعي المحسنة',
        'example_questions': '📝 أمثلة على الأسئلة التي يمكنك طرحها',
        'ask_your_question': 'اطرح سؤالك',
        'choose_example': 'اختر مثالاً أو اكتب سؤالك:',
        'custom_question': 'سؤال مخصص...',
        'your_question': 'سؤالك:',
        'ask': '🔍 اسأل',
        'analyzing': 'جاري التحليل...',
        'gpt_analysis_complete': '✨ اكتمل التحليل المدعوم بـ GPT',
        'analysis_complete': '✓ اكتمل التحليل',
        'answer': '**الإجابة:**',
        'ai_insights': '### 🧠 رؤى الذكاء الاصطناعي',
        'detailed_data': 'بيانات تفصيلية',
        'download_results': 'تحميل النتائج بصيغة CSV',
        'suggested_followup': '### 💭 أسئلة متابعة مقترحة',
        'please_enter_question': 'يرجى إدخال سؤال',
        'ai_chat': '💬 محادثة الذكاء الاصطناعي',
        'ai_chat_description': 'أجرِ محادثة مع الذكاء الاصطناعي حول بيانات مبيعاتك',
        'chat_input_placeholder': 'اطرح أسئلة متابعة أو أجرِ محادثة...',
        'thinking': 'جاري التفكير...',
        'clear_chat': '🗑️ مسح سجل المحادثة',
        'automatic_insights': '🎯 رؤى تلقائية',
        'generating_insights': 'جاري إنشاء الرؤى...',
        'no_insights': 'لم يتم الكشف عن رؤى مهمة',
        
        # Export & Reports
        'export_title': 'التصدير والتقارير',
        'generate_reports': 'إنشاء التقارير',
        'select_report_type': 'اختر نوع التقرير',
        'sales_summary': 'ملخص المبيعات',
        'customer_analysis': 'تحليل العملاء',
        'product_performance_report': 'أداء المنتجات',
        'rfm_segmentation_report': 'تصنيف RFM',
        'refill_predictions_report': 'توقعات إعادة الشراء',
        'cross_sell_opportunities': 'فرص البيع المتقاطع',
        'generate_report': 'إنشاء التقرير',
        'generating_report': 'جاري إنشاء التقرير...',
        'download_csv': 'تحميل CSV',
        'report_generated': 'تم إنشاء التقرير بنجاح!',
        
        # Common buttons and actions
        'loading': 'جاري تحميل البيانات النموذجية للعرض التوضيحي...',
        'error_loading': 'خطأ في تحميل البيانات: {error}',
        'failed_to_load': 'فشل تحميل البيانات. يرجى التحقق من ملفك.',
        'help_total_revenue': 'إجمالي الإيرادات من جميع المبيعات',
        'help_unique_orders': 'عدد الطلبات الفريدة',
        'help_unique_customers': 'عدد العملاء الفريدين',
        'help_avg_order': 'متوسط القيمة لكل طلب',
        'days': 'أيام',
        'items': 'منتجات',
        'times': 'مرات',
        'bundle': 'حزمة',
        'trend': 'الاتجاه',
        'count': 'العدد',
        'class': 'الفئة',
        'regularity': 'الانتظام',
    }
}

# OpenAI API configuration (optional, for AI features)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

